# Generated by Django 3.1 on 2020-09-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=300, upload_to='profile_pics', width_field=300),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('post_text', models.TextField(max_length=512)),
                ('post_image', models.ImageField(default='default.jpg', upload_to='post_images')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerver.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerver.profile')),
            ],
        ),
    ]
